name: seedr
services:
    seedr:
        container_name: seedr
        restart: unless-stopped
        network_mode: bridge
        ports:
            - 6688:8080
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Bucharest
        volumes:
            - ./data:/data
        image: ghcr.io/rursache/seedr:latest
